name: 'materialize_dbt'
version: '1.0.0'
config-version: 2

profile: 'ha_materialize'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  materialize_dbt:
    +materialized: view
    +schema: blue_green_slim


vars:
  deployment:
    staging:
      clusters:
        - transform
      schemas:
        - public_blue_green_slim
